### ISSUE TITLE
Perl error on tash setup sshd_config.conf (Mac OS Big Sur)

### ISSUE THREAD

**Issue by Snowmanko** [hudecof/ansible_ssh#2]
I have problem when setuping SSH with this role on this task:

**TASK [hudecof.ssh : setup sshd_config.conf]** 

```
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/4.2.0/libexec/lib/python3.9/site-packages/ansible/template/__init__.py", line 1094, in do_template
    res = j2_concat(rf)
  File "<template>", line 117, in root
  File "/usr/local/Cellar/ansible/4.2.0/libexec/lib/python3.9/site-packages/jinja2/runtime.py", line 349, in call
    return __obj(*args, **kwargs)
  File "/usr/local/Cellar/ansible/4.2.0/libexec/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'iteritems'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/4.2.0/libexec/lib/python3.9/site-packages/ansible/plugins/action/template.py", line 146, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
  File "/usr/local/Cellar/ansible/4.2.0/libexec/lib/python3.9/site-packages/ansible/template/__init__.py", line 1131, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'
fatal: [b2b-app]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'"
}

```

Can you please advise how to fix this perl error?
Problem will be on line 
```
Match {% for k,v in item.match.iteritems() %}{{ k }} {{ v|join(',') }} {% endfor %}
``` 
in templates/sshd_config.j2 file.

Thanks BR :-)

**Comment by hudecof** [comment]
Hi,

why perl error ? 
Please could you share the content of the variable `sshd_config_match`?

thanks
  hudecof

**Comment by Snowmanko** [comment]
Sure,

`
sshd_config_match:
  - match:
      Group: ['sftp-users']
    value:
      AllowAgentForwarding: "no"
      ChrootDirectory: "/srv/sftp/%u"
      AllowTcpForwarding: "no"
      X11Forwarding: "no"
      ForceCommand: "internal-sftp -l INFO"
`

**Comment by hudecof** [comment]
probloem is wth the python3 compatibility. In python3, dict.iteritems is no longer available. 
The template needs to be rewriten.

**Comment by hudecof** [comment]
check the new version `v0.3.2`. In my dev environment it works.

**Comment by hudecof** [comment]
Closing issue, with no response from the reporter.

**Comment by Snowmanko** [comment]
Worked like a charm! Thanks! <3
